### ISSUE TITLE
Outdated generated code error with dash_leaflet.express

### ISSUE THREAD

**Issue by kpoman** [thedirtyfew/dash-leaflet#158]
```
(venv) C:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard>pip install dash-leaflet -U
Requirement already satisfied: dash-leaflet in c:\users\kpoma\dev\djsa-dashboard\venv\lib\site-packages (0.1.23)
Requirement already satisfied: geobuf in c:\users\kpoma\dev\djsa-dashboard\venv\lib\site-packages (from dash-leaflet) (1.1.1)
Requirement already satisfied: click in c:\users\kpoma\dev\djsa-dashboard\venv\lib\site-packages (from 
geobuf->dash-leaflet) (8.1.3)
Requirement already satisfied: six in c:\users\kpoma\dev\djsa-dashboard\venv\lib\site-packages (from geobuf->dash-leaflet) (1.16.0)
Requirement already satisfied: protobuf in c:\users\kpoma\dev\djsa-dashboard\venv\lib\site-packages (from geobuf->dash-leaflet) (4.21.7)
Requirement already satisfied: colorama in c:\users\kpoma\dev\djsa-dashboard\venv\lib\site-packages (from click->geobuf->dash-leaflet) (0.4.5)

(venv) C:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard> c: && cd c:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard && cmd /C "c:\Users\kpoma\Dev\djsa-dashboard\venv\Scripts\python.exe c:\Users\kpoma\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher 65069 -- c:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard\pages\mapper.py "

(venv) C:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard> c: && cd c:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard && cmd /C "c:\Users\kpoma\Dev\djsa-dashboard\venv\Scripts\python.exe c:\Users\kpoma\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher 65109 -- c:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard\pages\mapper.py "
Traceback (most recent call last):
  File "c:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard\pages\mapper.py", line 9, in <module>
    import dash_leaflet.express as dlx
  File "c:\Users\kpoma\Dev\djsa-dashboard\venv\lib\site-packages\dash_leaflet\express.py", line 1, in <module>
    import geobuf
  File "c:\Users\kpoma\Dev\djsa-dashboard\venv\lib\site-packages\geobuf\__init__.py", line 1, in <module>
    from .encode import Encoder
  File "c:\Users\kpoma\Dev\djsa-dashboard\venv\lib\site-packages\geobuf\encode.py", line 9, in <module>    from . import geobuf_pb2
  File "c:\Users\kpoma\Dev\djsa-dashboard\venv\lib\site-packages\geobuf\geobuf_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "c:\Users\kpoma\Dev\djsa-dashboard\venv\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with 
protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates   

(venv) C:\Users\kpoma\Dev\djsa-dashboard\djsa-dashboard>
```

**Comment by kpoman** [comment]
fixed downgrading:
pip install protobuf==3.19.0
